# TF-IDF

TF-IDF (Term Frequency-Inverse Document Frequency) is a statistical measure used to evaluate the importance of a word in a document relative to a collection of documents (corpus). It is commonly used in information retrieval and text mining. TF-IDF is calculated by multiplying two metrics: Term Frequency (TF) and Inverse Document Frequency (IDF). TF-IDF vectors are often used in machine learning and natural language processing tasks to represent text data.

In [1]:
import pandas as pd

df = pd.read_csv("SMSSpamCollection.csv", sep="\t", names=["label", "message"])

In [2]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.tail()

label                                            message
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [4]:
# Data cleaning and preprocessing
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [5]:
corpus = []
for i in range(0, len(df)):
    review = re.sub("[^a-zA-Z]", " ", df["message"][i]) # keep only letters
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if word not in stopwords.words("english")]
    review = " ".join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [7]:
# TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=500)

In [8]:
X = vectorizer.fit_transform(corpus).toarray()

In [9]:
X.shape

(5572, 500)

In [10]:
import numpy as np

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3f" % x))

In [11]:
X

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.480, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.661, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000

In [12]:
vectorizer.vocabulary_

{'go': 155,
 'point': 326,
 'great': 163,
 'world': 483,
 'got': 161,
 'wat': 461,
 'ok': 294,
 'lar': 210,
 'wif': 472,
 'free': 143,
 'entry': 125,
 'win': 475,
 'st': 395,
 'may': 247,
 'text': 410,
 'receive': 346,
 'question': 339,
 'txt': 444,
 'rate': 341,
 'apply': 19,
 'dun': 114,
 'say': 361,
 'early': 116,
 'already': 10,
 'think': 417,
 'life': 223,
 'around': 21,
 'though': 420,
 'hey': 183,
 'week': 465,
 'word': 480,
 'back': 32,
 'like': 224,
 'fun': 148,
 'still': 399,
 'xxx': 490,
 'send': 368,
 'even': 127,
 'brother': 48,
 'speak': 393,
 'per': 310,
 'set': 371,
 'friend': 144,
 'network': 278,
 'customer': 89,
 'selected': 367,
 'prize': 334,
 'claim': 69,
 'call': 53,
 'code': 74,
 'valid': 450,
 'hour': 190,
 'mobile': 261,
 'month': 264,
 'update': 446,
 'latest': 214,
 'colour': 77,
 'camera': 57,
 'co': 73,
 'gonna': 159,
 'home': 187,
 'soon': 390,
 'want': 459,
 'talk': 407,
 'stuff': 402,
 'tonight': 432,
 'enough': 124,
 'today': 426,
 'chance': 63,
 'cash

In [13]:
# TF-IDF with N-grams
vectorizer_ngram = TfidfVectorizer(max_features=1500, ngram_range=(1, 2))
X_ngram = vectorizer_ngram.fit_transform(corpus).toarray()

In [14]:
X_ngram.shape

(5572, 1500)

In [15]:
X_ngram

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, ..., 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000

In [16]:
vectorizer_ngram.vocabulary_

{'go': 494,
 'point': 980,
 'crazy': 260,
 'available': 64,
 'bugis': 128,
 'great': 515,
 'world': 1465,
 'la': 650,
 'cine': 200,
 'got': 511,
 'wat': 1408,
 'ok': 898,
 'lar': 658,
 'wif': 1437,
 'free': 442,
 'entry': 370,
 'wkly': 1454,
 'comp': 230,
 'win': 1440,
 'cup': 263,
 'final': 417,
 'st': 1195,
 'may': 767,
 'text': 1263,
 'receive': 1035,
 'question': 1015,
 'std': 1206,
 'txt': 1329,
 'rate': 1021,
 'apply': 48,
 'free entry': 445,
 'rate apply': 1022,
 'dun': 341,
 'say': 1089,
 'early': 346,
 'already': 30,
 'nah': 845,
 'think': 1277,
 'usf': 1373,
 'life': 691,
 'around': 52,
 'though': 1284,
 'freemsg': 449,
 'hey': 560,
 'darling': 275,
 'week': 1422,
 'word': 1461,
 'back': 78,
 'like': 694,
 'fun': 464,
 'still': 1207,
 'xxx': 1482,
 'send': 1108,
 'even': 377,
 'brother': 123,
 'speak': 1184,
 'treat': 1313,
 'per': 941,
 'request': 1054,
 'set': 1116,
 'callertune': 156,
 'caller': 154,
 'press': 995,
 'copy': 247,
 'friend': 454,
 'winner': 1444,
 'valued': 

In [17]:
## Dependent feature
y = pd.get_dummies(df["label"], drop_first=True)
y

spam
0     False
1     False
2      True
3     False
4     False
...     ...
5567   True
5568  False
5569  False
5570  False
5571  False

[5572 rows x 1 columns]

In [18]:
# Convert y: True to 1 and False to 0
y = y.astype(int)

In [19]:
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [20]:
y.values.shape

(5572, 1)

In [21]:
# Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_ngram, y, test_size=0.2, random_state=42)

In [22]:
# Naive Bayes Classifier works best with sparse matrices
from sklearn.naive_bayes import MultinomialNB

In [23]:
spam_classifier = MultinomialNB()
spam_classifier.fit(X_train, y_train.values.ravel()) # to avoid warning

MultinomialNB()

In [24]:
y_pred = spam_classifier.predict(X_test)

In [25]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
# Accuracy matrix
from sklearn.metrics import accuracy_score, classification_report

In [27]:
accuracy_score(y_test, y_pred)

0.9820627802690582

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       0.97      0.89      0.93       149

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

