## About Dataset
Context This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content 5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset. Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('all_kindle_review.csv')

In [3]:
df.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [4]:
df.tail()

Unnamed: 0.1  Unnamed: 0        asin helpful  rating  \
11995         11995        2183  B001DUGORO  [0, 0]       4   
11996         11996        6272  B002JCSFSQ  [2, 2]       5   
11997         11997       12483  B0035N1V7K  [0, 1]       3   
11998         11998        3640  B001W1XT40  [1, 2]       1   
11999         11999       11398  B003370JUS  [5, 6]       3   

                                              reviewText   reviewTime  \
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400

In [5]:
df = df[['reviewText', 'rating']]

In [6]:
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [7]:
df.shape

(12000, 2)

In [8]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [9]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [10]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

## Preprocessing and Cleaning

In [11]:
df['rating'] = df['rating'].apply(lambda x: 1 if x > 3 else 0)

In [12]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [13]:
# Lower all the cases
df['reviewText'] = df['reviewText'].str.lower()

In [14]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       0
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       0
3  aggie is angela lansbury who carries pocketboo...       0
4  i did not expect this type of book to be in li...       1

In [15]:
import re
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

In [16]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

In [17]:
df.head()

reviewText  rating
0  jace rankin may short hes nothing mess man hau...       0
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       0
3  aggie angela lansbury carries pocketbooks inst...       0
4  expect type book library pleased find price right       1

In [18]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [19]:
def lemmatize_text(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [20]:
df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_text(x))

In [21]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       0
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       0
3  aggie angela lansbury carry pocketbook instead...       0
4  expect type book library pleased find price right       1

In [22]:
# Train Test Split
from sklearn.model_selection import train_test_split
X = df['reviewText']
y = df['rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [23]:
# Bag of Words with ngrams
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer(ngram_range=(1,2), max_features=5000)
X_train_bow = bow_vectorizer.fit_transform(X_train).toarray()
X_test_bow = bow_vectorizer.transform(X_test).toarray()

In [24]:
# TF-IDF with ngrams
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,2), max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train).toarray()
X_test_tfidf = tfidf_vectorizer.transform(X_test).toarray()

In [25]:
# Train the ML models
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [26]:
classifiers = {
    "Naive Bayes": GaussianNB(),
    "Logistic Regression": LogisticRegression(random_state=42, max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}
results = {}

In [27]:
for name, clf in classifiers.items():
    print(f"Training models with TF-IDF {name}...")
    # Train
    clf.fit(X_train_tfidf, y_train)
    # Predict
    y_pred = clf.predict(X_test_tfidf)
    # Evaluate
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    results[f"{name} (TF-IDF)"] = {
        'accuracy': accuracy,
        'classification_report': report,
        'confusion_matrix': cm
    }
    print(f"Accuracy: {accuracy}")
    print(f"Classification Report:\n{report}")
    print(f"Confusion Matrix:\n{cm}")


Training models with TF-IDF Naive Bayes...
Accuracy: 0.7845833333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.83      0.79      1200
           1       0.81      0.74      0.77      1200

    accuracy                           0.78      2400
   macro avg       0.79      0.78      0.78      2400
weighted avg       0.79      0.78      0.78      2400

Confusion Matrix:
[[999 201]
 [316 884]]
Training models with TF-IDF Logistic Regression...
Accuracy: 0.82875
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.82      0.83      1200
           1       0.82      0.84      0.83      1200

    accuracy                           0.83      2400
   macro avg       0.83      0.83      0.83      2400
weighted avg       0.83      0.83      0.83      2400

Confusion Matrix:
[[ 983  217]
 [ 194 1006]]
Training models with TF-IDF Random Forest...
Accuracy: 0.8004166666666667

In [28]:
for name, clf in classifiers.items():
    print(f"Training models with Bag of Words {name}...")
    # Train
    clf.fit(X_train_bow, y_train)
    # Predict
    y_pred = clf.predict(X_test_bow)
    # Evaluate
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    results[f"{name} (BoW)"] = {
        'accuracy': accuracy,
        'classification_report': report,
        'confusion_matrix': cm
    }
    print(f"Accuracy: {accuracy}")
    print(f"Classification Report:\n{report}")
    print(f"Confusion Matrix:\n{cm}")


Training models with Bag of Words Naive Bayes...
Accuracy: 0.7433333333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.88      0.77      1200
           1       0.83      0.61      0.70      1200

    accuracy                           0.74      2400
   macro avg       0.76      0.74      0.74      2400
weighted avg       0.76      0.74      0.74      2400

Confusion Matrix:
[[1053  147]
 [ 469  731]]
Training models with Bag of Words Logistic Regression...
Accuracy: 0.80375
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.80      0.80      1200
           1       0.80      0.81      0.80      1200

    accuracy                           0.80      2400
   macro avg       0.80      0.80      0.80      2400
weighted avg       0.80      0.80      0.80      2400

Confusion Matrix:
[[962 238]
 [233 967]]
Training models with Bag of Words Random Forest...
Accuracy: 